### ISSUE TITLE
Do we need "ResponsibleEntity"?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#11]
The vocabulary currently has a class for ResponsibleEntity. This would be a general class covering all of the various roles related to any of the WEMI entities. There are many sources of responsible entity properties (like id.loc.gov/relators), and some classes, like dct:Agent. 
>Definition | A resource that acts or has the power to act.

dct:Agent seems to fit the need but the question is whether we need a specific class for openWEMI to cover this.

NB: Other vocabularies have properties for roles but the class of those properties, like schema:Person, does not imply responsibility; that latter may be inherent in the property, like schema:author. id.loc.gov relators are subclassed to MADS:Authority, which covers all named entities, both creators and subjects and has its own meaning. The Library Reference Model has Agent with this definition which limits it to human actors in some sense:

>Being an agent requires having, or having had, the potential of intentional
relationships with instances of entities of bibliographic interest (works,
expressions, manifestations, items), whether that specific agent has ever
done so or not. Human beings are directly or indirectly the motive force
behind all such actions taken by all agents

**Comment by lagbolt** [comment]
Here's a diagram of how ResponsibleEntity would be used in practice.  (This is not to imply that the names are nailed down.)

![Example of ResponsibleEntity in FRBR](https://user-images.githubusercontent.com/13102982/230194464-4709ae2c-cf88-409c-abf8-86937e5babef.png)

**Comment by kcoyle** [comment]
Agreed we can use a class ResponsibleEntity
