### ISSUE TITLE
openWEMI logotype/logomark

### ISSUE THREAD

**Issue by nishad** [dcmi/openwemi#115]
openWEMI now uses a logotype as a logo (shown here); if there is another preferred logo to be used in dublincore.org, please finalize it and keep a copy in the repository (If possible, also in a vector file format, in SVG or EPS).

![openWEMI_logo](https://github.com/user-attachments/assets/213c1798-402a-45c2-a5dc-fc25cdf769a8)

**Comment by kcoyle** [comment]
done
