### ISSUE TITLE
Specification has absolute URLs for some images

### ISSUE THREAD

**Issue by nishad** [dcmi/openwemi#117]
The specification document available at `docs` has many absolute image urls.

Example:
https://github.com/dcmi/openwemi/blob/c93a1c38b61a237215a749a044a4347be14f2ad9/docs/index.md?plain=1#L37

Please correct them to relative URLs like:
https://github.com/dcmi/openwemi/blob/c93a1c38b61a237215a749a044a4347be14f2ad9/docs/index.md?plain=1#L95

This will otherwise effect the persistance of the images in the formal specification page at : https://www.dublincore.org/specifications/openwemi/specification

**Comment by kcoyle** [comment]
Done
