### ISSUE TITLE
Is subclass between WEMI and Endeavor enough?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#14]
Or do we need relationships between them?

**Comment by lagbolt** [comment]
A point of clarification (I hope):  subclass / superclass relates one class to another (like Endeavor and Work); a relationship relates one instance to another (like this-endeavor relates to that-work).

It's certainly possible to imagine sort of plausible relationships where the domain is Endeavor and the range is Work.  For example, "this-endeavor" <mentions> "this work" -- but I'm not sure why this belongs in OpenWEMI, at this level of abstraction.

**Comment by kcoyle** [comment]
Thanks, @lagbolt. Where I get doubts is when my brain sees WEMI as parts of a whole, which would make them parts of the Endeavor whole, not subclasses. In that view, it would not make sense for an Expression to be a type of Endeavor, but only for the expression of the work to be subclassed to Endeavor. In the classic FRBR view, WEMI is like a nested Russian doll, with E being inside W, M being inside E, etc. (The same works backward, IMEW). In fact, the relationship is that E expresses a W, meaning that in a sense E is E+W, not E alone. 

I think that our documentation needs to state that other than the relationships we provide there are no inherent or assumed relationships between the entities beyond the ones we provide, and that no entities are required in a model using openWEMI. But I still feel brain pain when I try to think of it that way.

**Comment by kcoyle** [comment]
The group agrees that the appropriate relationship is "subclass" and that Endeavor is a kind of organizing "bucket".
