### ISSUE TITLE
Keep the names?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#2]
The names Work, Expression, Manifestation, and Item were developed in a library catalog context. Are they:
1. sufficiently broad for openWEMI? 
2. confusing?
3. well known enough that we should continue with them?

**Comment by tombaker** [comment]
@kcoyle 
> well known enough that we should continue with them

To me, this is the most convincing reason. If openWEMI (or CWO) were to use different terminology, that could in itself be confusing, especially to people who might spot the resemblance to FRBR and wonder how (or whether) the two are related.

**Comment by seanpetiya** [comment]
Great to see these ideas taking shape in a new vocabulary! I think the names are sufficiently broad, and also generic enough to be utilized in non-library contexts. I've also always thought that each term helped convey the level of abstraction, from the concept or idea of a "work" to a tangible "item".

**Comment by kcoyle** [comment]
Robin: keep the names; the terminology has a legacy, a culture
heather: start from what people know and show how it is different. an evolution of WEMI

**Comment by kcoyle** [comment]
Resolved: keep work, expression, manifestation, and item.
