### ISSUE TITLE
expresses or expressionOf?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#25]
The linking properties between the WEMI entities are:
* expresses
* manifests
* instantiates

Would it be clearer if they were
* expressionOf
* manifestationOf
* instanceOf

This latter states what they *are* rather than what they *do*. Is this how people think of them?

**Comment by rsinger** [comment]
Verbs:
- expresses
- manifests
- instantiates

**Comment by rsinger** [comment]
Adjective(?) Gerund(?)

- expressionOf
- manifestationOf
- instanceOf

**Comment by kcoyle** [comment]
April 26 meeting - decided for the verb form
