### ISSUE TITLE
openWEMI? CWO?

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#3]
In an earlier presentation I was calling this the Creative Works Ontology, or CWO. I like the idea of openWEMI (h/t to Adrian Pohl) but if we want to distance ourselves some from FRBR/LRM and also promote the addition of classes not defined in those models, CWO may be better. It also works for those who haven't been "FRBR-ized" since "created works" is more descriptive of the vocabulary for those not familiar with the library models.

(I also joked that since Web Ontology Language is called "OWL", CWO could be pronounced "COW". I could seriously go for that.)

**Comment by tombaker** [comment]
@kcoyle @acka47
> idea of openWEMI (h/t to Adrian Pohl) 

I like openWEMI (unless we diverge from the Work Expression Manifestation Item terminology) - the acronym will be familiar to people who know FRBR, but without using the letters "F-R-B-R". And it is easy to pronounce.

> CWO could be pronounced "COW".

A nice idea, though I imagine alot of people would say "see double-u oh", especially if they only read about it.

**Comment by kcoyle** [comment]
Resolved: keep openWEMI, based on meetings of March 1-2
