### ISSUE TITLE
WEMI class in rm:Mixes?

### ISSUE THREAD

**Issue by philbarker** [dcmi/openwemi#72]
In this diagram
![image](https://github.com/dcmi/openwemi/assets/658047/2f8db575-5e67-4e7e-bf61-0a5cb02877d8)
Mix & Session are shown under Expression, which made me thing they are both intended to be Expressions.
However, in the table below it in the Primer rm:mixes is said to be a sub-property of Expresses:
![image](https://github.com/dcmi/openwemi/assets/658047/9c1a96f7-09d4-4618-a07d-9c67baa37493)
and so it should have the domain:Expression and range:Work. This would imply that Session is a Work and Mixes an Expression: that doesn't seem right.

There is no arrow drawn from Mixes to any WEMI class, so a solution might to make Mix a wemi:Work and rm:mixes a sub-property of dct:relation.

(Aside: while I think it is a great example I am a little worried about what a rabbit hole designing a recorded music ontology might turn out to be. For example, do we need other releases alongside Single, e.g. Album Track, Movie/TV Sound Track...)

**Comment by kcoyle** [comment]
Thanks, Phil. I think your analysis is correct; but I'm not totally sure about a solution. As I recall, at one point we had diagrams that showed the WEMI classes to be iterative - you could have a work of a work, an expression of an expression ... I don't remember any details but I think we instead created the "relatedWork" "relatedExpression" etc. In keeping with that, we could have:

rm:Session
    subclassOf openWEMI:Expression
rm:Mix
    subclassOf openWEMI:Expression
rm:mixof
    subpropertyOf openWEMI:relatedExpression

I'll try to adjust the diagram to reflect that, if that seems correct. 

I agree that a full ontology for recorded music would be overwhelming as an example. We need to stop before it goes beyond easy understanding. (Plus, I doubt if we really COULD create such an ontology.)

**Comment by kcoyle** [comment]
Here's another try:
![Copy of songWEMI2](https://github.com/dcmi/openwemi/assets/1564129/ed834da5-40e9-4074-909d-fb20907808ca)

**Comment by philbarker** [comment]
OK, that works. The diagram mixes the OpenWEMI properties in an example that uses subclasses but if we use the rm: properties that work if `rm:mixes rdfs:subPropertyOf wemi:relatedExpression .`  So something like:
![wemi4rm](https://github.com/dcmi/openwemi/assets/658047/c78e7fc5-cc3e-4edb-90db-b43de28ca37e)
 
I think I would like to show that the Mix expresses the Song, but let's leave the rabbits where they are.

**Comment by kcoyle** [comment]
This has been added to the Primer.
