### ISSUE TITLE
Where responsibleEntity property fits in

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#82]
The primer currently names `responsibleEntity` as a class. At the meeting on May 10,2023 it was decided to instead create responsibleEntity (rE) as a property. The trick is that because rE has no range, it isn't clear if we can integrate it into this diagram of relationships:
![relationships](https://github.com/dcmi/openwemi/assets/1564129/a9f9a5d4-aeda-4992-b74a-c353001b4998)
The tricky part here is that all of the other properties that we have defined have ranges, and those ranges are what is shown in this diagram.

So 
1. is there a place for rE in this diagram? (see the current [class diagram](https://private-user-images.githubusercontent.com/1564129/266374351-fa993378-921f-42b4-8585-c149fae574a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjQ5MjksIm5iZiI6MTcwNDkyNDYyOSwicGF0aCI6Ii8xNTY0MTI5LzI2NjM3NDM1MS1mYTk5MzM3OC05MjFmLTQyYjQtODU4NS1jMTQ5ZmFlNTc0YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjIxMDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRlZTlmYWEwMTk2NThkOWZlNjE2NjQ1ZWRjMGRlOGRmMDNhZmUzODFkYTJhNzUwMGFlYjExZjIzMDJiN2FmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._I7PKlL0mNpXPgljvTCDq57k3-tG6cxJsHTkv4qYYG8) in the Primer where it sits apart from the other classes. This diagram will also need to be fixed.)
2. Should the primer introduce all of the properties, including rE, as being explicitly in the domain of Endeavor and its subclasses?
3. or should we describe it elsewhere as an exception to the properties that have ranges? 
5. or should we leave off rE but make some recommendations of properties and classes in other vocabularies (dct, schema, ???) to complement E-WEMI?

I'm going to try to reproduce our reasons for including eR as a property in a comment below, and hope that others can clarify the gaps. I'm still not sure of the value of having eR in the domain of Endeavor, so that will be what I am trying to tease out.

**Comment by smrgeoinfo** [comment]
current class diagram is not public.

seems that responsibleEntity would be an agent in a role, which would be none of the classes in the diagram.  The responsibleParty pattern is pretty standard, isn't it (e.g. see ISO 19115-1)

**Comment by kcoyle** [comment]
> current class diagram is not public.

@smrgeoinfo - Richard, are you saying that you do not see the diagram in the opening comment, above? or ... ? please advise.

> seems that responsibleEntity would be an agent in a role, which would be none of the classes in the diagram

It is definitely the case that responsibleEntity is not in that diagram. It is, instead, (because of the primer and the vocabulary  being out of sync - mea culpa) in the diagram of classes. So the situation today is:

The [Primer](https://dcmi.github.io/openwemi/) lists among the classes a class `ResponsibleEntity`. 
The [vocabulary file](https://dcmi.github.io/openwemi/ns/openWEMI.ttl) does not include that class. Instead, it includes a property `responsibleEntity` defined as:

```
openwemi:responsibleEntity
  a rdf:Property ;
  rdfs:label "responsible entity"@en ;
  rdfs:comment "One responsible for the creation, production, distribution, maintenance, or ownership of a created entity."@en ;
  rdfs:isDefinedBy openwemi: ;
  dct:description "It is assumed that creations have been affected by an agent with the ability to act. The types of agents is very broad and not constrained by this property."@en ;
  rdfs:domain openwemi:Endeavor .
```
Where this property differs from all of the other properties in openWEMI is that it has a domain of `Endeavor` but no defined range; it has no defined relationship with the WEMI classes. That is what makes it hard to fit it into the diagram -- which may simply mean that it legitimately doesn't fit there.

This fact is what makes me wonder why we need this property since there seems to be no dearth of broadly defined properties (and classes) for this type of agent. My vague recollection is that the original idea of having a `ResponsibleEntity` class was seen to be either in conflict with, or redundant with, `dct:Agent`. One possibility would be to have `ResponsibleEntity` be subclassed to `dct:Agent`. I don't recall what the arguments were against that, however, but I admit to being wary of entanglements between the vocabularies.

What would we lose, if anything, by dropping this property from the vocabulary?

**Comment by thadguidry** [comment]
The definition of ResponsibleEntity on the Primer says “An agent with some responsibility related to a creation.”
The key term that is "related".  Looks like someone wanted to actually just have a Property for Endeavor.
But there is a whole ecosystem of potential Properties to be borrowed from other vocabularies and hang off of Endeavor.  I don't think that openWEMI is looking to absorb ecosystems into it's own vocabulary, right?  So I don't think ResponsibleEntity is fitting, just like CreationDate or CreationLocation and on and on, or any other classes that can relate to an Endeavor through various created properties.

So I think your Work, Expression, Manifestation, Item (WEMI) is sufficient.  Otherwise, you'll turn into (WEMIR) or worst (WEMIRCCLSDA) :-)

**Comment by kcoyle** [comment]
responsibleEntity  as been removed from the vocabulary - for now. We may reconsider at a later date, but for now this seems to be best.
